# Generated by Django 2.0.6 on 2018-06-25 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 25, 3, 57, 38, 786897)),
        ),
    ]
